Add a title
leon914/PROJECT-O-PIZZERIA pull request #1
Opened 2017-06-20 11:23 UTC by DalwinderBagdi

This PR contains:
 - 
 -

2017-06-20 12:00 UTC, leon914 commented
Tickets done in this pull request:
Prepare Restaurant class (main class) & all basic classes
List of tables - occupied by or not by a customer
As a waiter i want to unassign a customer from a table once they have finished
As a waiter i want to assign a customer to a table
List food and drinks - name and price
as a waiter i want to print out a menu of items

2017-06-21 13:50 UTC, ETFernandes requested changes

2017-06-21 13:50 UTC, ETFernandes commented on src/Customer.java
> +    private String name;
`final` on both fields. If fields are not going to be changed is a good practice to make them final, also the compiler can do some optimisations when things are `final`.

2017-06-21 13:50 UTC, ETFernandes commented on src/Customer.java
> +    public Customer(String name, int age) {
This should final, it tells the caller of this method that the parameters are not going to be modified.

2017-06-21 13:50 UTC, ETFernandes commented on src/Menu.java
> +     private Set foodMenu = new HashSet<Food>() {{
this should be `private Set<Food> foodMenu = new HashSet<>()`.

2017-06-21 13:50 UTC, ETFernandes commented on src/Menu.java
> +     private Set drinkMenu = new HashSet<Drink>()  {{
Same thing

2017-06-21 13:50 UTC, ETFernandes commented on src/Waiter.java
> +public class Waiter {
Same thing as the `Customer` class.

2017-06-21 13:50 UTC, ETFernandes commented on src/Table.java
> +public class Table {
Same thing as the `Customer` class.

2017-06-21 13:50 UTC, ETFernandes commented on src/Purchaseable.java
> +public abstract class Purchaseable {
Same thing as the `Customer` class.

2017-06-21 13:50 UTC, ETFernandes commented on src/Drink.java
> +    private String name;
You don't need this fields, since you extend `Purchaseable` and they are already there. You can remove every thing on this class except the constructor.

2017-06-21 13:50 UTC, ETFernandes commented on src/Drink.java
> +        this.name = name;
You should be using `super(name, price)`

2017-06-21 13:50 UTC, ETFernandes commented on src/Food.java
> +    private String name;
Same thing as the `Drink` class

2017-06-21 13:50 UTC, ETFernandes commented on src/Order.java
> +    public Order(Table tableOrder) {
Same thing as `Customer` class

2017-06-21 13:50 UTC, ETFernandes commented on src/Purchaseable.java
> +
You should define a constructor here and let the classes that extend this one use it by calling `super`

2017-06-21 13:50 UTC, ETFernandes commented on src/Restaurant.java
> +    public String getCustomers(Table table) {
this is bit confusing, my brother is going to explain you a simpler way of doing this :)

2017-06-21 14:13 UTC, leon914 commented on src/Menu.java
> +     private Set foodMenu = new HashSet<Food>() {{
this is now a List, but i tried that originally and intelliJ underlined it red which was weird

2017-06-21 14:13 UTC, leon914 commented on src/Customer.java
> +    public Customer(String name, int age) {
so like 'public final Customer(String name, int age)' ?

2017-06-21 14:28 UTC, leon914 commented on src/Order.java
> +    public Order(Table tableOrder) {
things change in here (like the contents of the order (the list)) so is making it final something i should do?

2017-06-22 13:55 UTC, merged