User interaction implemented
leon914/PROJECT-O-PIZZERIA pull request #2
Opened 2017-06-20 14:48 UTC by leon914

Has been reformatted so that the user can actually interact with the program.

2017-06-21 14:16 UTC, haaarry requested changes
Looking good, few comments. I will look over it again when they are done

2017-06-21 14:16 UTC, haaarry commented on src/Customer.java
> +    private Order order = null;
no need to set this to null as class variables are auto set to null.

2017-06-21 14:16 UTC, haaarry commented on src/Restaurant.java
> +                    break;
Might be good to have an error message as default letting the user know they have not inputed a valid option.

2017-06-21 14:16 UTC, haaarry commented on src/Table.java
> +    private Customer customer = null;
same as first comment

2017-06-21 14:16 UTC, haaarry commented on src/Table.java
> +    int tableNumber;
could make tableNumber private final and access it through getter

2017-06-21 14:16 UTC, haaarry commented on src/Waiter.java
> +//    }
do you need this commented out code?

2017-06-21 14:16 UTC, haaarry commented on src/Waiter.java
> +      //  restaurant.addOrder(new Order(table));
do you need this commented out code?

2017-06-21 14:16 UTC, haaarry commented on src/Restaurant.java
> +        tables.add(six);
could do this with a loop

2017-06-21 14:41 UTC, david-williams-sky requested changes
Additional feedback: '.class' or any other files generated in the build process should not be committed. Exclude them using .gitignore

2017-06-21 14:41 UTC, david-williams-sky commented on src/Customer.java
> +    public void addOrder(Order order) {
This function looks like it sets the customer order rather than adding an order (if it gets called more than once it will not add more orders - it will just overwrite the existing order) so I suggest calling it 'setOrder' rather than 'addOrder'.

Also the 'order' parameter should be set as 'final' (it is good practice to always specify final for method parameters)

2017-06-21 14:41 UTC, david-williams-sky commented on src/Customer.java
> +    private Order order = null;
No need to explicitly assign null here as class data members are implicitly set to null

2017-06-21 14:41 UTC, david-williams-sky commented on src/Main.java
> +    public static void main(String[] args) {
args parameter should be final

2017-06-21 14:41 UTC, david-williams-sky commented on src/Main.java
> +        Restaurant restaurant = new Restaurant();
restaurant variable should be final as it is not re-assigned

2017-06-21 14:41 UTC, david-williams-sky commented on src/Restaurant.java
> +    private List<Table> tables = new ArrayList<>();
final

2017-06-21 14:41 UTC, david-williams-sky commented on src/Restaurant.java
> +    private static Scanner scanner = new Scanner(System.in);
can be final - and then since a static final is a constant it should be named using full uppercase i.e.:

private static final Scanner SCANNER = new Scanner(System.in);

2017-06-21 14:41 UTC, david-williams-sky commented on src/Restaurant.java
> +    private Waiter carlos = new Waiter("Carlos");
final

2017-06-21 14:41 UTC, david-williams-sky commented on src/Restaurant.java
> +        tables.add(two);
I would suggest getting rid of the intermediate Table variables and doing something like tables.add(new Table(1)) etc. This will shorten your code and is still easily understandable

2017-06-21 14:41 UTC, david-williams-sky commented on src/Restaurant.java
> +        this.carlos.foodMenuPrint();
Avoid using 'this' unless you need to - e.g. when a parameter name matches a member variable name

2017-06-21 14:41 UTC, david-williams-sky commented on src/Restaurant.java
> +        int age = scanner.nextInt();
final

2017-06-21 14:41 UTC, david-williams-sky commented on src/Restaurant.java
> +        table--;
I suggest using "final int table = scanner.nextInt() - 1" rather than a separate line to do the decrement

2017-06-21 14:41 UTC, david-williams-sky commented on src/Restaurant.java
> +        tables.get(table).addCustomer(customer);
No need for intermediate customer variable here - just do:

tables.get(table).addCustomer(new Customer(name, age));

2017-06-21 14:41 UTC, david-williams-sky commented on src/Restaurant.java
> +        nominated--;
Same as above - do the decrement of the nominated variable on the same line and then you can make the variable final

2017-06-21 14:41 UTC, david-williams-sky commented on src/Restaurant.java
> +        this.tables.remove(nominated);
'this' not needed

2017-06-21 14:41 UTC, david-williams-sky commented on src/Table.java
> +    int tableNumber;
I think tableNumber can be private and final

2017-06-21 14:41 UTC, david-williams-sky commented on src/Table.java
> +    public Table(int tableNumber) {
final for tableNumber parameter

2017-06-21 14:41 UTC, david-williams-sky commented on src/Table.java
> +    public void addCustomer(Customer newCustomer) {
final

2017-06-21 14:41 UTC, david-williams-sky commented on src/Table.java
> +    private Customer customer = null;
null assignment not necessary

2017-06-21 14:41 UTC, david-williams-sky commented on src/Table.java
> +            this.customer = newCustomer;
'this' not necessary

2017-06-21 14:41 UTC, david-williams-sky commented on src/Table.java
> +        return this.customer;
'this' not necessary

2017-06-21 14:41 UTC, david-williams-sky commented on src/Waiter.java
> +    private Menu luciosMenu = new Menu();
Why is the menu called luciosMenu? Who is lucios - a waiter or a customer? In either case I don't think it should be part of a member variable name

2017-06-21 14:41 UTC, david-williams-sky commented on src/Waiter.java
> +      //  restaurant.addOrder(new Order(table));
Not sure what this method is doing if this line is commented out. Also it appears that the 'restuarant' parameter was never used and so should be removed

2017-06-21 14:41 UTC, david-williams-sky commented on src/Waiter.java
> +        this.luciosMenu.listFoodMenu();
'this' not required

2017-06-21 14:41 UTC, david-williams-sky commented on src/Waiter.java
> +        this.luciosMenu.listDrinkMenu();
'this' not required

2017-06-22 07:37 UTC, leon914 commented on src/Customer.java
> +    private Order order = null;
Ah i see

2017-06-22 08:33 UTC, leon914 commented
Gone through and made necessary changes, thank you :)

2017-06-26 11:59 UTC, merged